-- TABLESPACE 생성
CREATE TABLESPACE TBS_TEAM1
DATAFILE 'C:\TESTDATA\TBS_TEAM1.DBF'
SIZE 4M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
--==>> TABLESPACE TBS_TEAM1이(가) 생성되었습니다.


-- 계정생성
CREATE USER team1 IDENTIFIED BY java006$
DEFAULT TABLESPACE TBS_TEAM1;
--==>> User TEAM1이(가) 생성되었습니다.


